name: release

on:
  push:
    tags:
      - "*"


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: | 
          npm run build
          # to avoid parent directory
          cd dist && zip -r ../osu-bar-overlay.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: osu-bar-overlay.zip